version: '3.8'

services:
  # MySQL 服务
  mysql:
    working_dir: /app
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: dev_fs
      MYSQL_USER: dev_fs_user
      MYSQL_PASSWORD: dev_fs_user_pssd_Abc_123
    volumes:
      - mysql-data:/var/lib/mysql

  # # Redis 服务
  redis:
    working_dir: /app
    image: redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    privileged: true

  npm:
    working_dir: /app
    image: node:20-slim
    volumes:
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    command: sh -c "corepack enable && pnpm -v && pnpm install --registry=https://registry.npmmirror.com/"

  # NestJS 应用程序服务
  nestjs:
    working_dir: /app
    image: node:20-slim
    depends_on:
      - mysql
      - redis
      - npm
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: dev_fs_user
      MYSQL_PASSWORD: dev_fs_user_pssd_Abc_123
      MYSQL_DATABASE: dev_fs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: mysql://dev_fs_user:dev_fs_user_pssd_Abc_123@mysql:3306/dev_fs
    command: sh -c "corepack enable && pnpm run start:debug"

volumes:
  npm:
  mysql-data:
  redis-data:
networks:
  mysql:
  redis: